from heuristic import *
from expandBlocks import *
from deleteIsolated import *
from deleteIsolatedGroups import *
from join import *
from mergeColors import *
from addBuilding import *
from createWalls import *
from useOpenStreetMap import *
